package me.marin.lockout.generator;

import lombok.Getter;

import java.util.ArrayList;
import java.util.List;

import static me.marin.lockout.lockout.GoalType.*;

public class GoalGroup {

    private final static List<GoalGroup> GOAL_GROUPS = new ArrayList<>();

    public static final GoalGroup END = new GoalGroup(List.of(
            ENTER_END, EAT_CHORUS_FRUIT, OBTAIN_DRAGON_EGG, OBTAIN_END_ROD, GET_LEVITATION_STATUS_EFFECT, GET_THE_CITY_AT_THE_END_OF_THE_GAME_ADVANCEMENT, BREW_LINGERING_POTION, GET_REMOTE_GATEWAY_ADVANCEMENT
    ), 2);
    public static final GoalGroup END_STRUCTURE = new GoalGroup(List.of(
            GET_LEVITATION_STATUS_EFFECT, GET_THE_CITY_AT_THE_END_OF_THE_GAME_ADVANCEMENT
    ), 1);
    public static final GoalGroup TOOLS = new GoalGroup(List.of(
            OBTAIN_WOODEN_TOOLS, OBTAIN_STONE_TOOLS, OBTAIN_COPPER_TOOLS, OBTAIN_IRON_TOOLS, OBTAIN_GOLDEN_TOOLS, OBTAIN_DIAMOND_TOOLS
    ), 2);
    public static final GoalGroup DIAMOND = new GoalGroup(List.of(
            OBTAIN_DIAMOND_TOOLS, WEAR_DIAMOND_ARMOR
    ), 1);
    public static final GoalGroup ARMOR = new GoalGroup(List.of(
            WEAR_LEATHER_ARMOR, WEAR_COPPER_ARMOR, WEAR_IRON_ARMOR, WEAR_GOLDEN_ARMOR, WEAR_DIAMOND_ARMOR
    ), 1);
    public static final GoalGroup ARMOR_SPECIAL = new GoalGroup(List.of(
            WEAR_COLORED_LEATHER_ARMOR_PIECE, WEAR_UNIQUE_COLORED_LEATHER_ARMOR, WEAR_CARVED_PUMPKIN_FOR_5_MINUTES, WEAR_CHAIN_ARMOR_PIECE, FILL_ARMOR_STAND
    ), 2);
    public static final GoalGroup KILL_MOB = new GoalGroup(List.of(
            KILL_COLORED_SHEEP, KILL_ELDER_GUARDIAN, KILL_GHAST, KILL_PARCHED, KILL_SNOW_GOLEM, KILL_SNOW_GOLEM_IN_NETHER, KILL_SILVERFISH, KILL_STRAY, KILL_WITCH, KILL_ZOMBIE_VILLAGER, KILL_ZOGLIN, KILL_BAT,
            KILL_BREEZE_USING_WIND_CHARGE, KILL_SLIME, KILL_BOGGED, GET_WHOS_THE_PILLAGER_NOW_ADVANCEMENT
    ), 2);
    public static final GoalGroup SNOWMAN = new GoalGroup(List.of(
            KILL_SNOW_GOLEM, KILL_SNOW_GOLEM_IN_NETHER
    ), 1);
    public static final GoalGroup KILL_UNIQUE_HOSTILES = new GoalGroup(List.of(
            KILL_7_UNIQUE_HOSTILE_MOBS, KILL_10_UNIQUE_HOSTILE_MOBS, KILL_13_UNIQUE_HOSTILE_MOBS, KILL_15_UNIQUE_HOSTILE_MOBS
    ), 2);
    public static final GoalGroup KILL_HOSTILES_OF_TYPE = new GoalGroup(List.of(
            KILL_20_ARTHROPOD_MOBS, KILL_30_UNDEAD_MOBS
    ), 1);
    public static final GoalGroup FORTRESS = new GoalGroup(List.of(
            BREW_HEALING_POTION, BREW_INVISIBILITY_POTION, BREW_LINGERING_POTION, BREW_POISON_POTION, BREW_SWIFTNESS_POTION, BREW_WATER_BREATHING_POTION, BREW_WEAKNESS_POTION, BREW_FIRE_RESISTANCE_POTION, 
            PLACE_END_CRYSTAL, OBTAIN_ENDER_CHEST, USE_BREWING_STAND, OBTAIN_3_UNIQUE_HORSE_ARMOR
    ), 3);
    public static final GoalGroup BREW_POTION = new GoalGroup(List.of(
            BREW_HEALING_POTION, BREW_INVISIBILITY_POTION, BREW_LINGERING_POTION, BREW_POISON_POTION, BREW_SWIFTNESS_POTION, BREW_WATER_BREATHING_POTION, BREW_WEAKNESS_POTION, BREW_FIRE_RESISTANCE_POTION
    ), 1);
    public static final GoalGroup HORSE = new GoalGroup(List.of(
            TAME_HORSE, RIDE_HORSE, OBTAIN_3_UNIQUE_HORSE_ARMOR, EQUIP_HORSE_WITH_COLORED_LEATHER_ARMOR
    ), 1);
    public static final GoalGroup BREED = new GoalGroup(List.of(
            BREED_CHICKEN, BREED_COW, BREED_FOX, BREED_GOAT, BREED_HOGLIN, BREED_PIG, BREED_RABBIT, BREED_SHEEP, BREED_STRIDER, BREED_FROGS, BREED_ARMADILLO, BREED_CAMEL
    ), 2);
    public static final GoalGroup BREED_X_UNIQUE = new GoalGroup(List.of(
            BREED_4_UNIQUE_ANIMALS, BREED_6_UNIQUE_ANIMALS, BREED_8_UNIQUE_ANIMALS
    ), 2);
    public static final GoalGroup RIDE = new GoalGroup(List.of(
            RIDE_HORSE, RIDE_MINECART, RIDE_PIG, GET_THIS_BOAT_HAS_LEGS_ADVANCEMENT
    ), 2);
    public static final GoalGroup EAT_FOOD = new GoalGroup(List.of(
            EAT_CAKE, EAT_CHORUS_FRUIT, EAT_COOKIE, EAT_GLOW_BERRY, EAT_POISONOUS_POTATO, EAT_PUMPKIN_PIE, EAT_RABBIT_STEW, EAT_SUSPICIOUS_STEW, EAT_BEETROOT_SOUP, EAT_ALL_SOUPS
    ), 3);
    public static final GoalGroup EAT_X_UNIQUE_FOOD = new GoalGroup(List.of(
            EAT_5_UNIQUE_FOOD, EAT_10_UNIQUE_FOOD, EAT_15_UNIQUE_FOOD, EAT_20_UNIQUE_FOOD, EAT_25_UNIQUE_FOOD
    ), 2);
    public static final GoalGroup EFFECT = new GoalGroup(List.of(
            GET_ABSORPTION_STATUS_EFFECT, GET_BAD_OMEN_STATUS_EFFECT, GET_GLOWING_STATUS_EFFECT, GET_INFESTED_STATUS_EFFECT, GET_JUMP_BOOST_STATUS_EFFECT, GET_LEVITATION_STATUS_EFFECT,
            GET_MINING_FATIGUE_STATUS_EFFECT, GET_NAUSEA_STATUS_EFFECT, GET_POISON_STATUS_EFFECT, GET_WEAKNESS_STATUS_EFFECT
    ), 4);
    public static final GoalGroup EFFECT_X = new GoalGroup(List.of(
            GET_3_STATUS_EFFECTS_AT_ONCE, GET_4_STATUS_EFFECTS_AT_ONCE, GET_6_STATUS_EFFECTS_AT_ONCE
    ), 1);
    public static final GoalGroup HAVE_EFFECT_X_MINUTES = new GoalGroup(List.of(
            HAVE_EFFECTS_APPLIED_FOR_5_MINUTES, HAVE_EFFECTS_APPLIED_FOR_8_MINUTES, HAVE_EFFECTS_APPLIED_FOR_10_MINUTES
    ), 1);
    public static final GoalGroup DEATH_DAMAGE = new GoalGroup(List.of(
            DIE_BY_ANVIL, DIE_BY_BEE_STING, DIE_BY_BERRY_BUSH, DIE_BY_CACTUS, DIE_BY_FALLING_OFF_VINE, DIE_BY_FALLING_STALACTITE, DIE_BY_FIREWORK,
            DIE_BY_INTENTIONAL_GAME_DESIGN, DIE_BY_IRON_GOLEM, DIE_BY_MAGIC, DIE_BY_TNT_MINECART, OPPONENT_DIES, OPPONENT_DIES_3_TIMES,
            DEAL_400_DAMAGE, OPPONENT_TAKES_100_DAMAGE, TAKE_200_DAMAGE, DIE_TO_TRIDENT, DIE_TO_WARDEN
    ), 3);
    public static final GoalGroup BIOME = new GoalGroup(List.of(
            VISIT_BADLANDS_BIOME, VISIT_ICE_SPIKES_BIOME, VISIT_MUSHROOM_BIOME, GET_HOT_TOURIST_DESTINATIONS_ADVANCEMENT, VISIT_ALL_CAVE_BIOMES
    ), 1);
    public static final GoalGroup UNIQUE_BIOMES = new GoalGroup(List.of(
            VISIT_10_UNIQUE_BIOMES, VISIT_15_UNIQUE_BIOMES, VISIT_20_UNIQUE_BIOMES
    ), 2);
    public static final GoalGroup OPPONENT_HARD = new GoalGroup(List.of(
            OPPONENT_OBTAINS_CRAFTING_TABLE, OPPONENT_JUMPS, OPPONENT_TOUCHES_WATER
    ), 1);
    public static final GoalGroup OPPONENT_TAKES_DAMAGE = new GoalGroup(List.of(
            OPPONENT_TAKES_100_DAMAGE, OPPONENT_TAKES_FALL_DAMAGE, OPPONENT_CATCHES_ON_FIRE, OPPONENT_HIT_BY_ARROW, OPPONENT_HIT_BY_WIND_CHARGE
    ), 1);
    public static final GoalGroup OPPONENT_GOALS = new GoalGroup(List.of(
            OPPONENT_TAKES_100_DAMAGE, OPPONENT_TAKES_FALL_DAMAGE, OPPONENT_CATCHES_ON_FIRE,
            OPPONENT_OBTAINS_CRAFTING_TABLE, OPPONENT_JUMPS, OPPONENT_TOUCHES_WATER,
            OPPONENT_HIT_BY_EGG, OPPONENT_HIT_BY_SNOWBALL, OPPONENT_DIES, OPPONENT_DIES_3_TIMES, OPPONENT_HIT_BY_ARROW, OPPONENT_HIT_BY_WIND_CHARGE
    ), 3);
    public static final GoalGroup OPPONENT_DEATH_DAMAGE = new GoalGroup(List.of(
            OPPONENT_DIES, OPPONENT_DIES_3_TIMES, OPPONENT_TAKES_100_DAMAGE
    ), 1);
    public static final GoalGroup OPPONENT_HIT_BY = new GoalGroup(List.of(
            OPPONENT_HIT_BY_EGG, OPPONENT_HIT_BY_SNOWBALL, OPPONENT_HIT_BY_ARROW, OPPONENT_HIT_BY_WIND_CHARGE
    ), 1);
    public static final GoalGroup DAMAGE = new GoalGroup(List.of(
            DEAL_400_DAMAGE, OPPONENT_TAKES_100_DAMAGE, TAKE_200_DAMAGE, DAMAGED_BY_8_UNIQUE_SOURCES, DAMAGED_BY_12_UNIQUE_SOURCES, DAMAGED_BY_15_UNIQUE_SOURCES
    ), 2);
    public static final GoalGroup ADVANCEMENT = new GoalGroup(List.of(
            GET_10_ADVANCEMENTS, GET_20_ADVANCEMENTS, GET_30_ADVANCEMENTS,
            GET_A_TERRIBLE_FORTRESS_ADVANCEMENT, GET_ANY_SPYGLASS_ADVANCEMENT, GET_BULLSEYE_ADVANCEMENT,
            GET_EYE_SPY_ADVANCEMENT, GET_HOT_TOURIST_DESTINATIONS_ADVANCEMENT, GET_MOB_KABOB_ADVANCEMENT, GET_NOT_QUITE_NINE_LIVES_ADVANCEMENT,
            GET_OH_SHINY_ADVANCEMENT, GET_SNIPER_DUEL_ADVANCEMENT, GET_THE_CITY_AT_THE_END_OF_THE_GAME_ADVANCEMENT,
            GET_THIS_BOAT_HAS_LEGS_ADVANCEMENT, GET_THOSE_WERE_THE_DAYS_ADVANCEMENT, GET_WHAT_A_DEAL_ADVANCEMENT,
            GET_HIRED_HELP_ADVANCEMENT, GET_WAX_ON_ADVANCEMENT, GET_WAX_OFF_ADVANCEMENT, GET_MINECRAFT_TRIALS_EDITION_ADVANCEMENT, 
            GET_STAY_HYDRATED_ADVANCEMENT, GET_UNDER_LOCK_AND_KEY_ADVANCEMENT, GET_MOB_KABOB_ADVANCEMENT, GET_REMOTE_GATEWAY_ADVANCEMENT, GET_STAR_TRADER_ADVANCEMENT
    ), 4);
    public static final GoalGroup X_ADVANCEMENTS = new GoalGroup(List.of(
            GET_10_ADVANCEMENTS, GET_20_ADVANCEMENTS, GET_30_ADVANCEMENTS
    ), 2);
    public static final GoalGroup VILLAGE = new GoalGroup(List.of(
            EAT_PUMPKIN_PIE, EAT_COOKIE, GET_WHAT_A_DEAL_ADVANCEMENT, OBTAIN_BELL, DIE_BY_IRON_GOLEM, EAT_RABBIT_STEW,
            WEAR_CHAIN_ARMOR_PIECE, EAT_BEETROOT_SOUP, EAT_ALL_SOUPS
    ), 3);
    public static final GoalGroup MONUMENT = new GoalGroup(List.of(
            GET_MINING_FATIGUE_STATUS_EFFECT, KILL_ELDER_GUARDIAN, KILL_GUARDIAN, OBTAIN_SPONGE, DIE_BY_MAGIC, OBTAIN_SEA_LANTERN
    ), 1);
    public static final GoalGroup REDSTONE = new GoalGroup(List.of(
            OBTAIN_REDSTONE_COMPARATOR, OBTAIN_REDSTONE_LAMP, OBTAIN_CLOCK,
            OBTAIN_REDSTONE_REPEATER, OBTAIN_PISTON, OBTAIN_ACTIVATOR_RAIL,
            OBTAIN_DETECTOR_RAIL, OBTAIN_POWERED_RAIL, OBTAIN_DISPENSER,
            OBTAIN_OBSERVER
    ), 3);
    public static final GoalGroup TNT = new GoalGroup(List.of(
            OBTAIN_ALL_MINECARTS, OBTAIN_TNT, DIE_BY_TNT_MINECART
    ), 1);
    public static final GoalGroup STRIDER = new GoalGroup(List.of(
            BREED_STRIDER, GET_THIS_BOAT_HAS_LEGS_ADVANCEMENT, ATTACH_LEAD_TO_STRIDER
    ), 1);
    public static final GoalGroup SHEEP = new GoalGroup(List.of(
            BREED_SHEEP, KILL_COLORED_SHEEP
    ), 1);
    public static final GoalGroup COW = new GoalGroup(List.of(
            BREED_COW, ATTACH_LEAD_TO_COW
    ), 1);
    public static final GoalGroup FROG = new GoalGroup(List.of(
            BREED_FROGS, ATTACH_LEAD_TO_FROG
    ), 1);
    public static final GoalGroup FOX = new GoalGroup(List.of(
            BREED_FOX, ATTACH_LEAD_TO_FOX
    ), 1);
    public static final GoalGroup IRON_GOLEM = new GoalGroup(List.of(
            DIE_BY_IRON_GOLEM, GET_HIRED_HELP_ADVANCEMENT, ATTACH_LEAD_TO_IRON_GOLEM
    ), 1);
    public static final GoalGroup OBTAIN_ALL = new GoalGroup(List.of(
           OBTAIN_3_UNIQUE_HORSE_ARMOR, OBTAIN_ALL_MINECARTS, OBTAIN_ALL_PUMPKINS, OBTAIN_ALL_MUSHROOMS, OBTAIN_ALL_RAW_ORE_BLOCKS, 
           OBTAIN_4_UNIQUE_SEEDS, OBTAIN_ALL_TORCHES, OBTAIN_3_UNIQUE_BANNER_PATTERNS
    ), 2);
    public static final GoalGroup OBTAIN_SEEDS = new GoalGroup(List.of(
            OBTAIN_4_UNIQUE_SEEDS, OPPONENT_OBTAINS_SEEDS
    ), 1);
    public static final GoalGroup HONEY = new GoalGroup(List.of(
            DRINK_HONEY_BOTTLE, GET_WAX_ON_ADVANCEMENT, GET_WAX_OFF_ADVANCEMENT, OBTAIN_BEE_HIVE
    ), 1);
    public static final GoalGroup IRON_HEAVY = new GoalGroup(List.of(
            USE_ANVIL, DIE_BY_ANVIL, OBTAIN_ALL_MINECARTS, GET_HIRED_HELP_ADVANCEMENT
    ), 1);
    public static final GoalGroup LEATHER_HEAVY = new GoalGroup(List.of(
            WEAR_LEATHER_ARMOR, WEAR_UNIQUE_COLORED_LEATHER_ARMOR, FILL_BUNDLE_WITH_BUNDLES, EQUIP_HORSE_WITH_COLORED_LEATHER_ARMOR
    ), 1);
    public static final GoalGroup FIREWORKS = new GoalGroup(List.of(
            DIE_BY_FIREWORK, SHOOT_FIREWORK_FROM_CROSSBOW
    ), 1);
    public static final GoalGroup WOLF = new GoalGroup(List.of(
            TAME_WOLF, PUT_WOLF_ARMOR_ON_WOLF
    ), 1);
    public static final GoalGroup TRIAL_CHAMBERS = new GoalGroup(List.of(
            KILL_BREEZE_USING_WIND_CHARGE, KILL_SILVERFISH, GET_MINECRAFT_TRIALS_EDITION_ADVANCEMENT, GET_UNDER_LOCK_AND_KEY_ADVANCEMENT, OPPONENT_HIT_BY_WIND_CHARGE
    ), 1);
    public static final GoalGroup RAID = new GoalGroup(List.of(
            GET_BAD_OMEN_STATUS_EFFECT, KILL_ALL_RAID_MOBS
    ), 1);
    public static final GoalGroup BREAK_ITEM = new GoalGroup(List.of(
            BREAK_ANY_ARMOR, BREAK_ANY_TOOL
    ), 1);
    public static final GoalGroup SWAMP = new GoalGroup(List.of(
            BREED_FROGS, KILL_BOGGED, KILL_WITCH, KILL_SLIME
    ), 1);
    public static final GoalGroup HAVE_MORE = new GoalGroup(List.of(
            HAVE_MORE_UNIQUE_CRAFTS, HAVE_MORE_XP_LEVELS, HAVE_MOST_ADVANCEMENTS
    ), 1);
    public static final GoalGroup LEASH = new GoalGroup(List.of(
        ATTACH_LEAD_TO_CHERRY_CHEST_BOAT, ATTACH_LEAD_TO_COW, ATTACH_LEAD_TO_DOLPHIN, ATTACH_LEAD_TO_FOX, ATTACH_LEAD_TO_FROG, ATTACH_LEAD_TO_IRON_GOLEM, ATTACH_LEAD_TO_STRIDER
    ), 1);
    public static final GoalGroup LEASH_UNIQUE = new GoalGroup(List.of(
        LEASH_4_UNIQUE_ENTITIES_AT_ONCE, LEASH_6_UNIQUE_ENTITIES_AT_ONCE, LEASH_8_UNIQUE_ENTITIES_AT_ONCE
    ), 1);
    public static final GoalGroup CAMPFIRE = new GoalGroup(List.of(
        EXTINGUISH_CAMPFIRE_WITH_SHOVEL, FILL_CAMPFIRE
    ), 1);
    public static final GoalGroup SPYGLASS = new GoalGroup(List.of(
        LOOK_AT_HUSK, LOOK_AT_GUARDIAN, LOOK_AT_IRON_GOLEM, LOOK_AT_PIGLIN_BRUTE, LOOK_AT_HORSE, LOOK_AT_ENDERMAN
    ), 1);
    public static final GoalGroup SPYGLASS_UNIQUE = new GoalGroup(List.of(
        LOOK_AT_5_UNIQUE_MOBS, LOOK_AT_10_UNIQUE_MOBS, LOOK_AT_15_UNIQUE_MOBS, LOOK_AT_20_UNIQUE_MOBS
    ), 2);
    public static final GoalGroup ENRAGE = new GoalGroup(List.of(
        ENRAGE_ENDERMAN, ENRAGE_ZOMBIFIED_PIGLIN
    ), 1);
    public static final GoalGroup ENDERMAN = new GoalGroup(List.of(
        ENRAGE_ENDERMAN, LOOK_AT_ENDERMAN
    ), 1);


    public static final GoalGroup PICKS = new GoalGroup(new ArrayList<>(), Integer.MAX_VALUE);
    public static final GoalGroup BANS = new GoalGroup(new ArrayList<>(), Integer.MAX_VALUE);
    public static final GoalGroup PENDING_PICKS = new GoalGroup(new ArrayList<>(), Integer.MAX_VALUE);
    public static final GoalGroup PENDING_BANS = new GoalGroup(new ArrayList<>(), Integer.MAX_VALUE);

    // Groups for Mapping Categories in Search Widget
    public static final GoalGroup TOOLS_CATEGORY = new GoalGroup(List.of(
            OBTAIN_WOODEN_TOOLS, OBTAIN_STONE_TOOLS, OBTAIN_COPPER_TOOLS, OBTAIN_IRON_TOOLS, OBTAIN_GOLDEN_TOOLS, OBTAIN_DIAMOND_TOOLS, USE_BRUSH_ON_SUSPICIOUS_BLOCK, SHOOT_FIREWORK_FROM_CROSSBOW, 
            HAVE_YOUR_SHIELD_DISABLED, BREAK_ANY_TOOL
    ), Integer.MAX_VALUE);
    public static final GoalGroup ARMOR_CATEGORY = new GoalGroup(List.of(
            WEAR_LEATHER_ARMOR, WEAR_COPPER_ARMOR, WEAR_IRON_ARMOR, WEAR_GOLDEN_ARMOR, WEAR_DIAMOND_ARMOR, WEAR_FULL_ENCHANTED_ARMOR, WEAR_4_UNIQUE_ARMOR_PIECES, 
            WEAR_UNIQUE_COLORED_LEATHER_ARMOR, WEAR_CHAIN_ARMOR_PIECE, WEAR_COLORED_LEATHER_ARMOR_PIECE, BREAK_ANY_ARMOR, PUT_WOLF_ARMOR_ON_WOLF, 
            EQUIP_HORSE_WITH_COLORED_LEATHER_ARMOR, WEAR_CARVED_PUMPKIN_FOR_5_MINUTES
    ), Integer.MAX_VALUE);
    public static final GoalGroup TAME_CATEGORY = new GoalGroup(List.of(
            TAME_CAT, TAME_HORSE, TAME_PARROT, TAME_WOLF
    ), Integer.MAX_VALUE);
    public static final GoalGroup RIDE_CATEGORY = new GoalGroup(List.of(
            RIDE_HORSE, RIDE_MINECART, RIDE_PIG, RIDE_NAUTILUS, GET_THIS_BOAT_HAS_LEGS_ADVANCEMENT
    ), Integer.MAX_VALUE);
    public static final GoalGroup BIOMES_CATEGORY = new GoalGroup(List.of(
            VISIT_10_UNIQUE_BIOMES, VISIT_15_UNIQUE_BIOMES, VISIT_20_UNIQUE_BIOMES, VISIT_BADLANDS_BIOME, VISIT_ICE_SPIKES_BIOME, 
            VISIT_MUSHROOM_BIOME, VISIT_ALL_CAVE_BIOMES, GET_HOT_TOURIST_DESTINATIONS_ADVANCEMENT
    ), Integer.MAX_VALUE);
    public static final GoalGroup BREED_CATEGORY = new GoalGroup(List.of(
            BREED_4_UNIQUE_ANIMALS, BREED_6_UNIQUE_ANIMALS, BREED_8_UNIQUE_ANIMALS, BREED_ARMADILLO, BREED_CHICKEN, BREED_COW, BREED_CAMEL, BREED_FOX, 
            BREED_FROGS, BREED_GOAT, BREED_HOGLIN, BREED_PIG, BREED_RABBIT, BREED_SHEEP, BREED_STRIDER
    ), Integer.MAX_VALUE);
    public static final GoalGroup LEASH_CATEGORY = new GoalGroup(List.of(
            LEASH_4_UNIQUE_ENTITIES_AT_ONCE, LEASH_6_UNIQUE_ENTITIES_AT_ONCE, LEASH_8_UNIQUE_ENTITIES_AT_ONCE, ATTACH_LEAD_TO_CHERRY_CHEST_BOAT, ATTACH_LEAD_TO_COW, ATTACH_LEAD_TO_DOLPHIN, ATTACH_LEAD_TO_FOX, 
            ATTACH_LEAD_TO_FROG, ATTACH_LEAD_TO_IRON_GOLEM, ATTACH_LEAD_TO_STRIDER
    ), Integer.MAX_VALUE);
    public static final GoalGroup SPYGLASS_CATEGORY = new GoalGroup(List.of(
            LOOK_AT_5_UNIQUE_MOBS, LOOK_AT_10_UNIQUE_MOBS, LOOK_AT_15_UNIQUE_MOBS, LOOK_AT_20_UNIQUE_MOBS, LOOK_AT_HUSK, LOOK_AT_GUARDIAN, LOOK_AT_IRON_GOLEM, LOOK_AT_PIGLIN_BRUTE, LOOK_AT_HORSE, LOOK_AT_ENDERMAN
    ), Integer.MAX_VALUE);
    public static final GoalGroup BREWING_CATEGORY = new GoalGroup(List.of(
            USE_BREWING_STAND, BREW_FIRE_RESISTANCE_POTION, BREW_HEALING_POTION, BREW_INVISIBILITY_POTION, BREW_POISON_POTION, BREW_SWIFTNESS_POTION,
            BREW_WATER_BREATHING_POTION, BREW_WEAKNESS_POTION, BREW_LINGERING_POTION
    ), Integer.MAX_VALUE);
    public static final GoalGroup CONSUME_CATEGORY = new GoalGroup(List.of(
            EAT_5_UNIQUE_FOOD, EAT_10_UNIQUE_FOOD, EAT_15_UNIQUE_FOOD, EAT_20_UNIQUE_FOOD, EAT_25_UNIQUE_FOOD, EAT_ALL_SOUPS, EAT_BEETROOT_SOUP, EAT_CAKE, EAT_CHORUS_FRUIT, EAT_COOKIE, 
            EAT_GLOW_BERRY, EAT_POISONOUS_POTATO, EAT_PUMPKIN_PIE, EAT_RABBIT_STEW, EAT_SUSPICIOUS_STEW, DRINK_HONEY_BOTTLE, DRINK_WATER_BOTTLE
    ), Integer.MAX_VALUE);
    public static final GoalGroup DEATH_CATEGORY = new GoalGroup(List.of(
            DIE_BY_ANVIL, DIE_BY_BEE_STING, DIE_BY_BERRY_BUSH, DIE_BY_CACTUS, DIE_BY_DROWNING, DIE_BY_FALLING_OFF_VINE, DIE_BY_FALLING_STALACTITE, DIE_BY_FIREWORK, FREEZE_TO_DEATH, DIE_BY_INTENTIONAL_GAME_DESIGN, 
            DIE_BY_IRON_GOLEM, DIE_BY_MAGIC, DIE_BY_TNT_MINECART, DIE_TO_POLAR_BEAR, DIE_TO_PUFFERFISH, DIE_TO_WARDEN, DIE_TO_TRIDENT
    ), Integer.MAX_VALUE);
    public static final GoalGroup KILL_CATEGORY = new GoalGroup(List.of(
            KILL_ALL_RAID_MOBS, KILL_7_UNIQUE_HOSTILE_MOBS, KILL_10_UNIQUE_HOSTILE_MOBS, KILL_13_UNIQUE_HOSTILE_MOBS, KILL_15_UNIQUE_HOSTILE_MOBS, KILL_20_ARTHROPOD_MOBS, KILL_30_UNDEAD_MOBS, KILL_100_MOBS, KILL_BAT, 
            KILL_BLAZE_WITH_SNOWBALL, KILL_BOGGED, KILL_BREEZE_USING_WIND_CHARGE, KILL_COLORED_SHEEP, KILL_ELDER_GUARDIAN, KILL_GHAST, KILL_GUARDIAN, KILL_PARCHED, GET_WHOS_THE_PILLAGER_NOW_ADVANCEMENT, KILL_SILVERFISH, KILL_SNOW_GOLEM, KILL_SNOW_GOLEM_IN_NETHER, 
            KILL_SLIME, KILL_STRAY, KILL_WITCH, KILL_ZOGLIN, KILL_ZOMBIE_VILLAGER, ENRAGE_ENDERMAN, ENRAGE_ZOMBIFIED_PIGLIN, KILL_OTHER_PLAYER
    ), Integer.MAX_VALUE);
    public static final GoalGroup MINE_CATEGORY = new GoalGroup(List.of(
            MINE_CRAFTER, MINE_DIAMOND_ORE, MINE_EMERALD_ORE, MINE_MOB_SPAWNER, MINE_TURTLE_EGG
    ), Integer.MAX_VALUE);
    public static final GoalGroup ENTER_STRUCTURE_DIMENSION_CATEGORY = new GoalGroup(List.of(
            GET_MINECRAFT_TRIALS_EDITION_ADVANCEMENT, ENTER_NETHER, GET_THOSE_WERE_THE_DAYS_ADVANCEMENT, GET_A_TERRIBLE_FORTRESS_ADVANCEMENT, GET_EYE_SPY_ADVANCEMENT, ENTER_END, GET_REMOTE_GATEWAY_ADVANCEMENT, GET_THE_CITY_AT_THE_END_OF_THE_GAME_ADVANCEMENT
    ), Integer.MAX_VALUE);
    public static final GoalGroup OPPONENT_DOES_X_CATEGORY = new GoalGroup(List.of(
            OPPONENT_DIES, OPPONENT_DIES_3_TIMES, OPPONENT_OBTAINS_CRAFTING_TABLE, OPPONENT_OBTAINS_OBSIDIAN, OPPONENT_OBTAINS_SEEDS, OPPONENT_EATS_FOOD, OPPONENT_JUMPS, 
            OPPONENT_HIT_BY_ARROW, OPPONENT_HIT_BY_EGG, OPPONENT_HIT_BY_SNOWBALL, OPPONENT_HIT_BY_WIND_CHARGE, OPPONENT_TAKES_100_DAMAGE, OPPONENT_TAKES_FALL_DAMAGE, OPPONENT_CATCHES_ON_FIRE, OPPONENT_TOUCHES_WATER
    ), Integer.MAX_VALUE);
    public static final GoalGroup WORKSTATION_CATEGORY = new GoalGroup(List.of(
            OBTAIN_7_UNIQUE_WORKSTATIONS, USE_ANVIL, USE_CAULDRON, USE_COMPOSTER, USE_ENCHANTING_TABLE, USE_GRINDSTONE, LOCK_MAP_USING_CARTOGRAPHY_TABLE, USE_JUKEBOX, USE_LOOM, TUNE_NOTE_BLOCK, USE_SMITHING_TABLE, USE_STONECUTTER
    ), Integer.MAX_VALUE);
    public static final GoalGroup FILL_INTERFACE_CATEGORY = new GoalGroup(List.of(
            FILL_ARMOR_STAND, FILL_BUNDLE_WITH_BUNDLES, FILL_CAMPFIRE, FILL_CHISELED_BOOKSHELF, FILL_DECORATED_POT, FILL_INVENTORY_UNIQUE_ITEMS, FILL_SHELF_WITH_SHELVES
    ), Integer.MAX_VALUE);
    public static final GoalGroup OBTAIN_CATEGORY = new GoalGroup(List.of(
            OBTAIN_2_UNIQUE_ARMOR_TRIMS, OBTAIN_3_UNIQUE_BANNER_PATTERNS, OBTAIN_3_UNIQUE_MUSIC_DISCS, OBTAIN_4_UNIQUE_SAPLINGS, OBTAIN_4_UNIQUE_SEEDS, OBTAIN_5_UNIQUE_PRESSURE_PLATES, OBTAIN_6_UNIQUE_BRICK_TYPES, OBTAIN_64_ARROWS, OBTAIN_64_COARSE_DIRT, OBTAIN_64_COLORED_CONCRETE, 
            OBTAIN_64_COLORED_GLASS, OBTAIN_64_COLORED_TERRACOTTA, OBTAIN_64_COLORED_WOOL, OBTAIN_6_UNIQUE_BUCKETS, OBTAIN_6_UNIQUE_FLOWERS,OBTAIN_64_FIREFLY_BUSHES, OBTAIN_64_GLOW_LICHEN, OBTAIN_ALL_FURNACE_TYPES, OBTAIN_3_UNIQUE_HORSE_ARMOR, OBTAIN_ALL_MINECARTS, 
            OBTAIN_ALL_MUSHROOMS, OBTAIN_ALL_PUMPKINS, OBTAIN_ALL_RAW_ORE_BLOCKS, OBTAIN_ALL_TORCHES, OBTAIN_ACTIVATOR_RAIL, OBTAIN_AMETHYST_BLOCK, OBTAIN_ANCIENT_DEBRIS, OBTAIN_BEE_HIVE, OBTAIN_BELL, OBTAIN_BLOCK_OF_RESIN, OBTAIN_BOOKSHELF, OBTAIN_BRICK_WALL, 
            OBTAIN_CALIBRATED_SCULK_SENSOR, OBTAIN_CLOCK, OBTAIN_COBWEB, OBTAIN_COLORED_GLAZED_TERRACOTTA, OBTAIN_COLORED_HARNESS, OBTAIN_DAYLIGHT_DETECTOR, OBTAIN_DEAD_BUSH, OBTAIN_DETECTOR_RAIL, OBTAIN_DIAMOND_BLOCK, OBTAIN_DISPENSER, OBTAIN_DRAGON_EGG, 
            OBTAIN_DRIED_KELP_BLOCK, OBTAIN_EMERALD_BLOCK, OBTAIN_ENCHANT_BOTTLE, OBTAIN_ENDER_CHEST, OBTAIN_END_ROD, OBTAIN_FLOWERING_AZALEA, OBTAIN_GILDED_BLACKSTONE, OBTAIN_HEART_OF_THE_SEA, OBTAIN_LODESTONE, OBTAIN_MOSSY_STONE_BRICK_WALL, OBTAIN_MUD_BRICK_WALL, OBTAIN_NAUTILUS_ARMOR, 
            OBTAIN_OBSERVER, OBTAIN_PISTON, OBTAIN_POTTERY_SHERD, OBTAIN_POWDER_SNOW_BUCKET, OBTAIN_POWERED_RAIL, OBTAIN_REDSTONE_COMPARATOR, OBTAIN_REDSTONE_LAMP, OBTAIN_REDSTONE_REPEATER, OBTAIN_RED_NETHER_BRICK_STAIRS, OBTAIN_SCAFFOLDING, OBTAIN_SEA_LANTERN, 
            OBTAIN_SMOOTH_QUARTZ_STAIRS, OBTAIN_SOUL_CAMPFIRE, OBTAIN_SOUL_LANTERN, OBTAIN_SPONGE, OBTAIN_TINTED_GLASS, OBTAIN_TNT, OBTAIN_TROPICAL_FISH_BUCKET, OBTAIN_WITHER_SKELETON_SKULL
    ), Integer.MAX_VALUE);
    public static final GoalGroup EXPERIENCE_CATEGORY = new GoalGroup(List.of(
            REACH_EXP_LEVEL_15, REACH_EXP_LEVEL_30
    ), Integer.MAX_VALUE);
    public static final GoalGroup HAVE_MORE_CATEGORY = new GoalGroup(List.of(
            HAVE_MORE_XP_LEVELS, HAVE_MORE_CREEPER_KILLS, HAVE_MORE_UNIQUE_CRAFTS, HAVE_MOST_ADVANCEMENTS, HAVE_MORE_UNIQUE_SMELTS
    ), Integer.MAX_VALUE);
    public static final GoalGroup ADVANCEMENTS_CATEGORY = new GoalGroup(List.of(
            GET_10_ADVANCEMENTS, GET_20_ADVANCEMENTS, GET_30_ADVANCEMENTS, GET_ANY_SPYGLASS_ADVANCEMENT, GET_BULLSEYE_ADVANCEMENT, GET_HIRED_HELP_ADVANCEMENT, GET_MOB_KABOB_ADVANCEMENT, GET_NOT_QUITE_NINE_LIVES_ADVANCEMENT, GET_OH_SHINY_ADVANCEMENT, GET_SNIPER_DUEL_ADVANCEMENT, 
            GET_STAY_HYDRATED_ADVANCEMENT, GET_UNDER_LOCK_AND_KEY_ADVANCEMENT, GET_WAX_ON_ADVANCEMENT, GET_WAX_OFF_ADVANCEMENT, GET_WHAT_A_DEAL_ADVANCEMENT, GET_STAR_TRADER_ADVANCEMENT
    ), Integer.MAX_VALUE);
    public static final GoalGroup STATUS_EFFECT_CATEGORY = new GoalGroup(List.of(
            GET_3_STATUS_EFFECTS_AT_ONCE, GET_4_STATUS_EFFECTS_AT_ONCE, GET_6_STATUS_EFFECTS_AT_ONCE, HAVE_EFFECTS_APPLIED_FOR_5_MINUTES, HAVE_EFFECTS_APPLIED_FOR_8_MINUTES, HAVE_EFFECTS_APPLIED_FOR_10_MINUTES, GET_ABSORPTION_STATUS_EFFECT, 
            GET_BAD_OMEN_STATUS_EFFECT, GET_GLOWING_STATUS_EFFECT, GET_INFESTED_STATUS_EFFECT, GET_JUMP_BOOST_STATUS_EFFECT, GET_LEVITATION_STATUS_EFFECT, GET_MINING_FATIGUE_STATUS_EFFECT, GET_NAUSEA_STATUS_EFFECT, 
            GET_POISON_STATUS_EFFECT, GET_WEAKNESS_STATUS_EFFECT, REMOVE_STATUS_EFFECT_USING_MILK
    ), Integer.MAX_VALUE);
    public static final GoalGroup STATISTICS_CATEGORY = new GoalGroup(List.of(
            CROUCH_100_M, SWIM_500_M, SPRINT_1_KM, BOAT_2KM, TAKE_200_DAMAGE, DEAL_400_DAMAGE
    ), Integer.MAX_VALUE);
    public static final GoalGroup MISCELLANEOUS_CATEGORY = new GoalGroup(List.of(
            DAMAGED_BY_8_UNIQUE_SOURCES, DAMAGED_BY_12_UNIQUE_SOURCES, DAMAGED_BY_15_UNIQUE_SOURCES, CONSTRUCT_COPPER_GOLEM, EMPTY_HUNGER_BAR, EXTINGUISH_CAMPFIRE_WITH_SHOVEL, ITEM_FRAME_IN_ITEM_FRAME, LIGHT_CANDLE, PLACE_END_CRYSTAL, PLACE_PAINTING, 
            PUT_FLOWER_IN_POT, PUT_BANNER_ON_SHIELD, REACH_NETHER_ROOF, REACH_BEDROCK, REACH_HEIGHT_LIMIT, RIGHT_CLICK_BANNER_WITH_MAP, TOOT_GOAT_HORN, 
            USE_GLOW_INK, OBTAIN_WRITTEN_BOOK
    ), Integer.MAX_VALUE);
    




    private static int CUSTOM_LIMIT = Integer.MAX_VALUE;
    
    // Maps goal ID to player name who picked/banned it
    private static final java.util.Map<String, String> GOAL_TO_PLAYER_MAP = new java.util.HashMap<>();

    public static void setCustomLimit(int limit) {
        CUSTOM_LIMIT = limit;
    }

    public static int getCustomLimit() {
        return CUSTOM_LIMIT;
    }
    
    public static void setGoalPlayer(String goalId, String playerName) {
        GOAL_TO_PLAYER_MAP.put(goalId, playerName);
    }
    
    public static String getGoalPlayer(String goalId) {
        return GOAL_TO_PLAYER_MAP.get(goalId);
    }
    
    public static void clearGoalPlayers() {
        GOAL_TO_PLAYER_MAP.clear();
    }

    static {
        KILL_UNIQUE_HOSTILES.requirePredecessor.add(KILL_13_UNIQUE_HOSTILE_MOBS);
        KILL_UNIQUE_HOSTILES.requirePredecessor.add(KILL_15_UNIQUE_HOSTILE_MOBS);
        BREED_X_UNIQUE.requirePredecessor.add(BREED_8_UNIQUE_ANIMALS);
        EAT_X_UNIQUE_FOOD.requirePredecessor.add(EAT_20_UNIQUE_FOOD);
        EAT_X_UNIQUE_FOOD.requirePredecessor.add(EAT_25_UNIQUE_FOOD);
        X_ADVANCEMENTS.requirePredecessor.add(GET_30_ADVANCEMENTS);
        UNIQUE_BIOMES.requirePredecessor.add(VISIT_20_UNIQUE_BIOMES);
        SPYGLASS_UNIQUE.requirePredecessor.add(LOOK_AT_15_UNIQUE_MOBS);
        SPYGLASS_UNIQUE.requirePredecessor.add(LOOK_AT_20_UNIQUE_MOBS);
    }

    static {
        GOAL_GROUPS.add(END);
        GOAL_GROUPS.add(END_STRUCTURE);
        GOAL_GROUPS.add(TOOLS);
        GOAL_GROUPS.add(DIAMOND);
        GOAL_GROUPS.add(ARMOR);
        GOAL_GROUPS.add(ARMOR_SPECIAL);
        GOAL_GROUPS.add(KILL_MOB);
        GOAL_GROUPS.add(SNOWMAN);
        GOAL_GROUPS.add(KILL_UNIQUE_HOSTILES);
        GOAL_GROUPS.add(KILL_HOSTILES_OF_TYPE);
        GOAL_GROUPS.add(FORTRESS);
        GOAL_GROUPS.add(BREW_POTION);
        GOAL_GROUPS.add(HORSE);
        GOAL_GROUPS.add(BREED);
        GOAL_GROUPS.add(BREED_X_UNIQUE);
        GOAL_GROUPS.add(RIDE);
        GOAL_GROUPS.add(EAT_FOOD);
        GOAL_GROUPS.add(EAT_X_UNIQUE_FOOD);
        GOAL_GROUPS.add(EFFECT);
        GOAL_GROUPS.add(EFFECT_X);
        GOAL_GROUPS.add(HAVE_EFFECT_X_MINUTES);
        GOAL_GROUPS.add(DEATH_DAMAGE);
        GOAL_GROUPS.add(BIOME);
        GOAL_GROUPS.add(UNIQUE_BIOMES);
        GOAL_GROUPS.add(OPPONENT_HARD);
        GOAL_GROUPS.add(OPPONENT_TAKES_DAMAGE);
        GOAL_GROUPS.add(OPPONENT_GOALS);
        GOAL_GROUPS.add(OPPONENT_DEATH_DAMAGE);
        GOAL_GROUPS.add(OPPONENT_HIT_BY);
        GOAL_GROUPS.add(DAMAGE);
        GOAL_GROUPS.add(ADVANCEMENT);
        GOAL_GROUPS.add(X_ADVANCEMENTS);
        GOAL_GROUPS.add(VILLAGE);
        GOAL_GROUPS.add(MONUMENT);
        GOAL_GROUPS.add(REDSTONE);
        GOAL_GROUPS.add(TNT);
        GOAL_GROUPS.add(STRIDER);
        GOAL_GROUPS.add(SHEEP);
        GOAL_GROUPS.add(OBTAIN_ALL);
        GOAL_GROUPS.add(OBTAIN_SEEDS);
        GOAL_GROUPS.add(HONEY);
        GOAL_GROUPS.add(IRON_HEAVY);
        GOAL_GROUPS.add(LEATHER_HEAVY);
        GOAL_GROUPS.add(FIREWORKS);
        GOAL_GROUPS.add(WOLF);
        GOAL_GROUPS.add(TRIAL_CHAMBERS);
        GOAL_GROUPS.add(RAID);
        GOAL_GROUPS.add(BREAK_ITEM);
        GOAL_GROUPS.add(SWAMP);
        GOAL_GROUPS.add(HAVE_MORE);
        GOAL_GROUPS.add(LEASH);
        GOAL_GROUPS.add(LEASH_UNIQUE);
        GOAL_GROUPS.add(CAMPFIRE);
        GOAL_GROUPS.add(SPYGLASS);
        GOAL_GROUPS.add(ENRAGE);
        GOAL_GROUPS.add(ENDERMAN);
    }


    @Getter
    private final List<String> goals;
    @Getter
    private final int limit;
    private final List<String> requirePredecessor = new ArrayList<>();

    private GoalGroup(List<String> goals, int limit) {
        this.goals = goals;
        this.limit = limit;
    }

    private int countMatches(List<String> boardGoals) {
        int count = 0;
        for (String goal : boardGoals) {
            if (goals.contains(goal)) {
                count++;
            }
        }
        return count;
    }

    private static List<GoalGroup> findGroups(String goalType) {
        List<GoalGroup> found = new ArrayList<>();
        for (GoalGroup group : GOAL_GROUPS) {
            if (group.goals.contains(goalType)) {
                found.add(group);
            }
        }

        return found;
    }

    public static boolean canAdd(String goalType, List<String> board) {
        List<GoalGroup> groups = findGroups(goalType);

        for (GoalGroup group : groups) {
            if (group.countMatches(board) + 1 > group.getLimit()) {
                return false;
            }
            if (group.requirePredecessor.contains(goalType)) {
                if (!hasPredecessorInGroup(goalType, board, group)) {
                    return false;
                }
            }
        }

        return true;
    }

    private static boolean hasPredecessorInGroup(String goalType, List<String> board, GoalGroup group) {
        int max = group.goals.indexOf(goalType);
        if (max < 0) return false;
        for (int i = 0; i < max; i++) {
            String goal = group.goals.get(i);
            if (board.contains(goal)) {
                // Lockout.log(goalType + " has a predecessor " + goal + ".");
                return true;
            }
        }
        return false;
    }

    public boolean containsGoal(String goal) {
        return goals.contains(goal);
    }

}
